/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosRouteImport } from './routes/_pos'
import { Route as PosIndexRouteImport } from './routes/_pos.index'
import { Route as PosSuccessRouteImport } from './routes/_pos.success'
import { Route as PosNewOrderRouteImport } from './routes/_pos.new-order'
import { Route as PosCheckoutRouteImport } from './routes/_pos.checkout'

const PosRoute = PosRouteImport.update({
  id: '/_pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const PosSuccessRoute = PosSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PosRoute,
} as any)
const PosNewOrderRoute = PosNewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => PosRoute,
} as any)
const PosCheckoutRoute = PosCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PosIndexRoute
  '/checkout': typeof PosCheckoutRoute
  '/new-order': typeof PosNewOrderRoute
  '/success': typeof PosSuccessRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof PosCheckoutRoute
  '/new-order': typeof PosNewOrderRoute
  '/success': typeof PosSuccessRoute
  '/': typeof PosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pos': typeof PosRouteWithChildren
  '/_pos/checkout': typeof PosCheckoutRoute
  '/_pos/new-order': typeof PosNewOrderRoute
  '/_pos/success': typeof PosSuccessRoute
  '/_pos/': typeof PosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/new-order' | '/success'
  fileRoutesByTo: FileRoutesByTo
  to: '/checkout' | '/new-order' | '/success' | '/'
  id:
    | '__root__'
    | '/_pos'
    | '/_pos/checkout'
    | '/_pos/new-order'
    | '/_pos/success'
    | '/_pos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PosRoute: typeof PosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pos': {
      id: '/_pos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pos/': {
      id: '/_pos/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/success': {
      id: '/_pos/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof PosSuccessRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/new-order': {
      id: '/_pos/new-order'
      path: '/new-order'
      fullPath: '/new-order'
      preLoaderRoute: typeof PosNewOrderRouteImport
      parentRoute: typeof PosRoute
    }
    '/_pos/checkout': {
      id: '/_pos/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PosCheckoutRouteImport
      parentRoute: typeof PosRoute
    }
  }
}

interface PosRouteChildren {
  PosCheckoutRoute: typeof PosCheckoutRoute
  PosNewOrderRoute: typeof PosNewOrderRoute
  PosSuccessRoute: typeof PosSuccessRoute
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosCheckoutRoute: PosCheckoutRoute,
  PosNewOrderRoute: PosNewOrderRoute,
  PosSuccessRoute: PosSuccessRoute,
  PosIndexRoute: PosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PosRoute: PosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
